/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accesodatos.xestion;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;

/**
 *
 * @author erifc
 */
public class xestionAppMainForm extends javax.swing.JFrame {

    boolean dbComprobada = false;
    /**
     * Creates new form xestionApp
     */

    private static final String pathProvincias = "/provincias.json";
    private static Provincias provincias = new Provincias();

    public xestionAppMainForm() {
        initComponents();
        this.setLocationRelativeTo(null); //Abrir app en el centro de la pantalla

        //Para solo comprobar la db al inicio de la app
        if (!dbComprobada) {

            String db = "xestionAppDB.db";
            File dbFile = new File(db);
            Connection con = null;
            System.out.println("dbFile: " + dbFile.getAbsolutePath());
            //Creación base de datos si no existe
            if (!dbFile.exists()) {
                DB.createDatabase(db);
            }

            con = DB.connectDatabase(db);

            /*Creación de tablas (en el código de cada tabla 
            se especifica que se creee si no existe)*/
            DB.createTable(con, DB.getSqlCustomers());
            DB.createTable(con, DB.getSqlEmployees());
            DB.createTable(con, DB.getSqlItems());
            DB.createTable(con, DB.getSqlProvinces());
            DB.createTable(con, DB.getSqlStores());
            DB.createTable(con, DB.getSqlStockItemStore());
            DB.createTable(con, DB.getSqlHoursEmployeeStore());

            DB.desconnetDatabase(con);

            dbComprobada = true;
        }

        //Insertamos las provincias de España
        LoadProvinces();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        btnEmployees = new javax.swing.JButton();
        btnStores = new javax.swing.JButton();
        btnItems = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnTitularesElPais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("XESTIÓN FRANQUICIA");

        btnEmployees.setText("Empleados");
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });

        btnStores.setText("Tiendas");
        btnStores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoresActionPerformed(evt);
            }
        });

        btnItems.setText("Productos");
        btnItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsActionPerformed(evt);
            }
        });

        btnCustomers.setText("Clientes");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnTitularesElPais.setText("Leer titulares El País");
        btnTitularesElPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitularesElPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTitularesElPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnStores, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStores, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTitularesElPais, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        // TODO add your handling code here:
        EmployeesDialog ed = new EmployeesDialog(this, true);
        ed.setVisible(true);
    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void btnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsActionPerformed
        // TODO add your handling code here:
        ItemsDialog id = new ItemsDialog(this, true);
        id.setVisible(true);
    }//GEN-LAST:event_btnItemsActionPerformed

    private void btnStoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoresActionPerformed
        // TODO add your handling code here:
        StoresDialog sd = new StoresDialog(this, true);
        sd.setVisible(true);
    }//GEN-LAST:event_btnStoresActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        CustomersDialog cd = new CustomersDialog(this, true);
        cd.setVisible(true);
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnTitularesElPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitularesElPaisActionPerformed
        // TODO add your handling code here:
        ElPaisDialog epd = new ElPaisDialog(this,false);
        epd.setVisible(true);
    }//GEN-LAST:event_btnTitularesElPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xestionAppMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xestionAppMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xestionAppMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xestionAppMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(xestionAppMainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                new xestionAppMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnItems;
    private javax.swing.JButton btnStores;
    private javax.swing.JButton btnTitularesElPais;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables

    //Cargar provincias España
    private void LoadProvinces() {
        // jsonToObj devuelvo un Object, para pasarlo a nuestra clase tenemos que hacer así
        ManageJson mj = new ManageJson();
        provincias = Provincias.class.cast(mj.jsonToObj(pathProvincias, Provincias.class));
        System.err.println("prueba contenido provinces");
        LinkedList<Province> listProvincias = provincias.getProvincias();
        Iterator it = listProvincias.iterator();

        String db = "xestionAppDB.db";
        Connection con = null;
        con = DB.connectDatabase(db);

        while (it.hasNext()) {
            Province tempProvince = (Province) it.next();
            System.out.println("provincia: " + tempProvince.toString());
            DB.insertProvince(con, Integer.valueOf(tempProvince.getId()), tempProvince.getNome());
        }
        System.err.println(provincias.toString());
        DB.desconnetDatabase(con);
    }
}
